### ISSUE TITLE
Bug fixes

### ISSUE THREAD

**Issue by flockermush** [tonyheadford/m68k#1]
Hi,

I've used your emulator in a project to make an SMSQ/E machine. ( downloadable at www.wlenerz.com/SMSQmulator) Whilst doing so, I had to make quite some bugfixes in your code. I'd like to give the corrected code back to you. How do I do that?

W

**Comment by alexwinston** [comment]
Hey guys are these changes some where I could get them?  It doesn't look like they were ever added back and the link isn't working anymore.  I am trying to get the emulator to run a version of uClinux compiled for m68k and was running into some issues.  Before I dig in I wanted to see if these changes might help.

**Comment by tonyheadford** [comment]
I've just had a hunt around on my hard drive and found the zip with Wolfgang's fixes in. I will try and merge these into the codebase this weekend.

**Comment by tonyheadford** [comment]
@alexwinston I've integrated the changes @flockermush contributed. Enjoy.

**Comment by alexwinston** [comment]
Great work guys, you have a top notch emulator here!  I was finally able to get uClinux running, which is no small feat considering all the other emulators I have tried aren't able to do this, including the Musashi emulator.

**Comment by tonyheadford** [comment]
@alexwinston that's really cool.  Thanks for getting in touch and giving me the incentive to apply those bug fixes. I'm stoked that you're able to use my emulator in your project.
