### ISSUE TITLE
ANDI_TO_CCR mask is incorrect

### ISSUE THREAD

**Issue by sam-ellis** [tonyheadford/m68k#3]
ANDI_TO_CCR masks bits 0x31 instead of bits 0x1f:

		int s = cpu.fetchPCWord() & 0x0031;           // mask out all but 5 lower bits

**Comment by tonyheadford** [comment]
Yes I agree, this is not right. Thanks.

**Comment by sam-ellis** [comment]
Confirmed resolved by c0eece2f85bfba766f3d3b0e7c902a1e8d877cd4.
