### ISSUE TITLE
NEG_X instructions must not set Z flag

### ISSUE THREAD

**Issue by sam-ellis** [tonyheadford/m68k#4]
According to M68k manual, NEGX instructions have the following behaviour for Z flag:

Z — Cleared if the result is nonzero; unchanged otherwise.

The current implementation always sets Z flag if value is zero, where as it should be left unchanged.

**Comment by tonyheadford** [comment]
Agree, good catch, thanks.

**Comment by sam-ellis** [comment]
Confirmed fixed by c0eece2f85bfba766f3d3b0e7c902a1e8d877cd4.
