### ISSUE TITLE
ROL/ROR instructions fail to clear C flag when shift is zero

### ISSUE THREAD

**Issue by sam-ellis** [tonyheadford/m68k#5]
ROL/ROR instructions fail to clear the C flag when shift is zero according to M68K manual:

C — Set according to the last bit rotated out of the operand; **cleared when the rotate
count is zero.**

Problem is due to code for adjusting C flag in CpuCore.java being skipped in the case shift count is zero.

**Comment by tonyheadford** [comment]
Agree this is wrong. Thanks for the extra info.

**Comment by sam-ellis** [comment]
Confirmed fixed by c0eece2f85bfba766f3d3b0e7c902a1e8d877cd4.
