### ISSUE TITLE
MOVEP.L Dx, (Ay) incorrectly transfers word from register instead of long

### ISSUE THREAD

**Issue by sam-ellis** [tonyheadford/m68k#6]
MOVEP.L Dx, (Ay) reads a word value from Dx instead of long in MOVEP.r2m_long():

int val = cpu.getDataRegister**Word**((opcode >> 9) & 0x07);

**Comment by tonyheadford** [comment]
Yes, thanks good spot.

**Comment by sam-ellis** [comment]
Confirmed fixed by 94c7836b72d94c16e4cc34621314c29737477261.
