### ISSUE TITLE
NEGX.B/.W fails to preserve Z flag in some cases

### ISSUE THREAD

**Issue by sam-ellis** [tonyheadford/m68k#7]
NEGX.B/.W fails to set Z flag in some cases. Consider:

D0 = 0x000000FF, X=1
NEGX.B D0

should result in:
0x0 - 0xFF - 1 = 0x00 (Z set)

but actually results in:
0x0 - 0x000000FF - 1 = 0xFFFFFF00 (of which only lower 8-bits are stored, but Z-flag is computed from whole 32-bits and is cleared)

So the problem is the Z-flag is computed from the whole 32-bit result rather than the 8-bit result. Same problem for NEGX.W. Must compute Z-flag taking into account the size of the result.

**Comment by tonyheadford** [comment]
Thanks for the info, you are quite right.

**Comment by fedex81** [comment]
Hello,
shouldn't this read: "NEGX fails to preserve Z flag in some cases"?

D0 = 0x000000FF, X=1, Z=1
NEGX.B D0
should result in:
D0 = 0x00,  Z=1
--
D0 = 0x000000FF, X=1, Z=0
NEGX.B D0
should result in:
D0 = 0x00,  Z=0

**Comment by sam-ellis** [comment]
Yes

**Comment by sam-ellis** [comment]
Confirmed fixed by c0eece2f85bfba766f3d3b0e7c902a1e8d877cd4.
